# -*- coding: utf-8 -*-
"""crypto_prices.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5Ixkk6_XQ62WU2KbPui5PULUejhwJsL
"""



"""BTC, ETH, SOL price COINGECKO API

"""

import requests
url = "https://api.coingecko.com/api/v3/simple/price"
params = {
    "ids": "bitcoin,ethereum,solana",
    "vs_currencies": "usd"
}

response = requests.get(url, params=params)

if response.status_code == 200:
    prices = response.json()
    print("Current Cryptocurrency Prices (USD):")
    print(f"Bitcoin (BTC): ${prices['bitcoin']['usd']}")
    print(f"Ethereum (ETH): ${prices['ethereum']['usd']}")

else:
    print(f"Failed to fetch prices. Status code: {response.status_code}")

